#!/bin/sh
# versionを表示するオプションが不明なコマンドに対してバージョンを表示する
# 
# execute:
#   env.sh command

set -Ceuo pipefail

# オプションの存在を確認する
# 引数: コマンド名 オプション
# 戻り値: 0: 存在する, 1: 存在しない
function has_option() {
	local cmd=$1
	local option=$2
	local _=$($cmd $option &> /dev/null)
	return $?
}

# option_list=(--hoge)
option_list=(--version -version -V -v)
command=$1

if [[ $# == 0 ]]; then
	echo "command not found"
	exit 1
fi

for option in ${option_list[@]}; do
	ret=$(has_option $1 $option)
	if [[ $? == 0 ]]; then
		$1 $option
		exit 0
	fi
	echo "not found $option"
done
